#!/bin/bash
set -euo pipefail
source /etc/profile.d/modules.sh
module load samtools

# =============================================================================
# Human vs. chimp ChIP-seq read splitting -- STEP 2: RUN SNPSPLIT + MERGE
# =============================================================================
# Uses the 2 dual-hybrid genomes/SNP files from the genome-prep script
# (H20961_C3649_hap1 and H20961_C3649_hap2) to split each sample's BAM
# (already mapped to both dual-masked genomes) into human (genome1) vs.
# chimp (genome2) reads, once per haplotype pair. The genome1 (human) BAMs
# from both rounds are then merged into one human BAM/FASTQ per sample, and
# likewise for genome2 (chimp), re-marking duplicates after merging.
#
# Assumes each sample was already mapped to both dual-masked genomes
# =============================================================================

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
BASE_DIR=/.../.../ # path to bam files in this format: /mapping_human*_chimp*/${sample}/bowtie2/${sample}_unique_alignments_dedup.bam
SPLIT_DIR=${BASE_DIR}/split_round1 # output directory
HAP1_SNP_FILE=/.../H20961_C3649_hap1_genomeprep/all_C3649.hg38.hap1.bam_SNPs_H20961.hg38.hap1.bam_reference.based_on_hg38.txt # generated by  01_snpsplit_genome_prep.sh
HAP2_SNP_FILE=/.../H20961_C3649_hap2_genomeprep/all_C3649.hg38.hap2.bam_SNPs_H20961.hg38.hap2.bam_reference.based_on_hg38.txt # generated by  01_snpsplit_genome_prep.sh

# ChIP-seq samples to process (H3K27ac reps 1-4, SNAI2 reps 1-4)
namelist=(
  s15_CNCCP4_HL130_rep1_aH3K27ac_deeper
  s16_CNCCP4_HL130_rep2_aH3K27ac_deeper
  s17_CNCCP4_HL130_rep3_aH3K27ac_deeper
  s18_CNCCP4_HL130_rep4_aH3K27ac_deeper
  s19_CNCCP4_HL130_rep1_aSNAI2_deeper
  s20_CNCCP4_HL130_rep2_aSNAI2_deeper
  s21_CNCCP4_HL130_rep3_aSNAI2_deeper
  s24_CNCCP4_HL130_rep4_aSNAI2_deeper
  inp7_CNCCP4_HL130_rep1
  inp8_CNCCP4_HL130_rep2
  inp9_CNCCP4_HL130_rep3
  inp10_CNCCP4_HL130_rep4
  s20_ChIPlib8_HL130_aSNAI2
  s21_ChIPlib8_HL130_aH3K27ac
  s26_ChIPlib8_HL130_inp
)


mkdir -p "$SPLIT_DIR"
cd "$SPLIT_DIR"

# ---------------------------------------------------------------------------
# STEP 1 -- Run SNPsplit on the hap1 and hap2 alignments for one sample.
# In SNPsplit's output, genome1 = human, genome2 = chimp (for both rounds).
# ---------------------------------------------------------------------------
run_snpsplit_for_sample() {
    local sample="$1"

    mkdir -p "${sample}_output_H20961_C3649_hap1"
    (
      cd "${sample}_output_H20961_C3649_hap1"
      SNPsplit --paired \
        --snp_file "$HAP1_SNP_FILE" \
        "${BASE_DIR}/mapping_human1_chimp1/${sample}/bowtie2/${sample}_unique_alignments_dedup.bam"
    )

    mkdir -p "${sample}_output_H20961_C3649_hap2"
    (
      cd "${sample}_output_H20961_C3649_hap2"
      SNPsplit --paired \
        --snp_file "$HAP2_SNP_FILE" \
        "${BASE_DIR}/mapping_human2_chimp2/${sample}/bowtie2/${sample}_unique_alignments_dedup.bam"
    )
}

for sample in "${namelist[@]}"; do
    run_snpsplit_for_sample "$sample"
done

# ---------------------------------------------------------------------------
# STEP 2 -- Merge genome1 (human) or genome2 (chimp) BAMs from the hap1-split
# and hap2-split rounds for one sample; mark/remove duplicates on the merged
# BAM; convert to paired FASTQ.
# ---------------------------------------------------------------------------
merge_species_bam_to_fastq() {
    local sample="$1"      # sample name
    local genome="$2"      # "genome1" (human) or "genome2" (chimp)
    local species="$3"     # "human" or "chimp" -- used for output naming

    local hap1_bam="${sample}_output_H20961_C3649_hap1/${sample}_unique_alignments_dedup.${genome}.bam"
    local hap2_bam="${sample}_output_H20961_C3649_hap2/${sample}_unique_alignments_dedup.${genome}.bam"
    local out_prefix="${sample}/${sample}_merged_${species}"

    samtools merge -u -@ 8 - "$hap1_bam" "$hap2_bam" \
      | samtools collate -@ 8 -u -O - \
      | samtools fixmate -@ 8 -u -m - - \
      | samtools sort -@ 8 -u - \
      | samtools markdup -@ 8 -r - "${out_prefix}.bam"

    samtools index "${out_prefix}.bam"

    samtools sort -n -@ 8 -u "${out_prefix}.bam" \
      | samtools fastq -@ 8 \
          -1 "${out_prefix}_reads_unique_R1.fastq.gz" \
          -2 "${out_prefix}_reads_unique_R2.fastq.gz" \
          -0 /dev/null -s /dev/null -
}

for sample in "${namelist[@]}"; do
    mkdir -p "${sample}"
    merge_species_bam_to_fastq "$sample" genome1 human
    merge_species_bam_to_fastq "$sample" genome2 chimp
done

echo "SNPsplit + merge done. Human/chimp FASTQs are in ${SPLIT_DIR}/<sample>/"
